[colors]
transparent_background_colors = true

[font]
size = 16

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "O"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
dynamic_padding = true
opacity = 0.85
startup_mode = "Maximized"

[general]
live_config_reload = true
working_directory = "None"
import = [
    "/usr/share/alacritty/themes/papercolor_dark.toml"
]
