#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Whyme Lyu"
email = "callme5long@gmail.com"

[ui]
pager = "delta"
diff-formatter = ":git"

[aliases]
di = ["diff"]
ic = ["commit", "-i"]
movelocals = ["rebase", "-r", "description(glob:\":local:*\")", "-B", "@"]

[git]
private-commits = "description(glob:':local:*')"
