#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Whyme Lyu"
email = "callme5long@gmail.com"

[ui]
pager = "delta"
diff-formatter = ":git"
default-command = ["log", "--stat"]
merge-editor = "vimdiff"

[revset-aliases]
'locals()' = "subject(glob:':local:*')"
'tug_target()' = "heads(::@- ~ locals())"

[aliases]
di = ["diff"]
ic = ["commit", "-i"]
tuglocals = ["rebase", "-r", "locals()", "-B", "@"]
ph = ["git", "push"]
tug = ["bookmark", "move", "-f", "heads(::@- & bookmarks())", "-t", "tug_target()"]
showtug = ["log", "-r", "tug_target()"]
up = ["util", "exec", "--", "bash", "-c", """
  set -eu
  jj tuglocals
  jj tug
  jj ph
""", ""]
# dn is short for down
dn = ["git", "fetch"]

[git]
private-commits = "locals()"

[templates]
draft_commit_description = '''
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
