[main]
anchor = top
fields = exec,name,generic
font = monospace:size=24,LXGW Bright:size=16,Font Awesome 7 Free,Font Awesome 7 Brand
hide-before-typing = yes
launch-prefix = uwsm app --
list-executables-in-path = yes
show-actions = yes
tabs = 4
terminal = foot -a '{cmd}' -T '{cmd}' {cmd}

# Rose Pine:
# https://github.com/bomgar/rose-pine-fuzzel/blob/main/themes/rose-pine.ini
[colors]
background=#19172466
text=#e0def4ff
prompt=#e0def4ff
placeholder=#6e6a86ff
input=#e0def4ff
match=#ebbcbaff
selection=#403d52ff
selection-text=#e0def4ff
selection-match=#ebbcbaff
counter=#f6c177ff
border=#ebbcbaff
[border]

[dmenu]
exit-immediately-if-empty = yes

[key-bindings]
