[main]
term = foot-extra-direct
include = /usr/share/foot/themes/paper-color
font=monospace:size=16,LXGW Bright:size=16,Font Awesome 7 Free,Font Awesome 7 Brand
initial-window-mode = maximized

[colors]
alpha=0.85

[key-bindings]
search-start=Control+Shift+r Mod1+r
show-urls-copy=Control+Shift+y
clipboard-copy=Control+Shift+c XF86Copy Mod4+c
clipboard-paste=Control+Shift+v XF86Paste Mod4+v
spawn-terminal=Control+Shift+n Mod1+n
pipe-command-output=[wl-copy] Control+Shift+p
unicode-input=none

# vim: ft=dosini
